tests: add loop arg
* fixes the following error when running 'make test'
* dont ask me why it works

FAILED tests/test_app.py::test_app_sargo - TypeError: Page.__init__() missing 1 required positional argument: 'loop'
FAILED tests/test_app.py::test_app_beyond2lte - TypeError: Page.__init__() missing 1 required positional argument: 'loop'

Signed-off-by: SirRGB <sirrgb@proton.me>